<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.codeprep</groupId>
    <artifactId>designPatterns</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>00solid</module>
        <module>01memento-pattern</module>
        <module>02observer-pattern</module>
        <module>03strategy-pattern</module>
        <module>04command-pattern</module>
        <module>05templatemethod-pattern</module>
        <module>06iterator-pattern</module>
        <module>07state-pattern</module>
		<module>09mediator-pattern</module>
        <module>10singleton-pattern</module>
        <module>11factory-pattern</module>
        <module>12abstract-factory-pattern</module>
        <module>13builder-pattern</module>
        <module>14prototype-pattern</module>
        <module>15adapter-pattern</module>
        <module>16decorator-pattern</module>
        <module>17proxy-pattern</module>
        <module>18composite-pattern</module>
        <module>19facade-pattern</module>
    </modules>

    <properties>
        <maven.compiler.source>24</maven.compiler.source>
        <maven.compiler.target>24</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <junit.version>5.10.0</junit.version>
        <mockito.version>5.17.0</mockito.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>${mockito.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-junit-jupiter</artifactId>
                <version>${mockito.version}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>